// <auto-generated />
using System;
using API.UnidadEmpleo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations.UnidadEmpleoDb
{
    [DbContext(typeof(UnidadEmpleoDbContext))]
    [Migration("20260421205440_start")]
    partial class start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Seguridad.Domain.Audit.EntityChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EntityChangeLogs");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Blob")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("LinkId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoAnexo")
                        .HasColumnType("int");

                    b.Property<int>("TipoArchivo")
                        .HasColumnType("int");

                    b.Property<int>("TipoLink")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Aspirante", b =>
                {
                    b.Property<string>("Curp")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Apellido_Materno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Apellido_Paterno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoAcreditaEscolaridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntreCalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EscolaridadConcluidaTrunca")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado_Civil")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha_Nacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("Foto")
                        .HasColumnType("int");

                    b.Property<int>("Grado_Escolaridad")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PensionaodISSEMYM")
                        .HasColumnType("bit");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coordenadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("Curp");

                    b.ToTable("Aspirante");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.CartaCompromiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaCompromiso")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<int>("IdSoliciud")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSoliciud");

                    b.ToTable("CartaCompromiso");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Cuerpo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Numero")
                        .HasMaxLength(120)
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Corporacion");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSoliciud")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ingreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resultado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Salida")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoEvaluacion")
                        .HasColumnType("int");

                    b.Property<bool>("revalorable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdSoliciud");

                    b.ToTable("Evaluacion");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Referencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido_Materno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Apellido_Paterno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntreCalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSoliciud")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parentesco")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coordenadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSoliciud");

                    b.ToTable("Referencia");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Region", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActaNacimiento")
                        .HasColumnType("bit");

                    b.Property<bool>("CartasRecomendacion")
                        .HasColumnType("bit");

                    b.Property<bool>("CartillaLiberada")
                        .HasColumnType("bit");

                    b.Property<bool>("CertificadoEstudios")
                        .HasColumnType("bit");

                    b.Property<bool>("ComprobanteDomicilio")
                        .HasColumnType("bit");

                    b.Property<string>("CorporacionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Croquis")
                        .HasColumnType("bit");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("nvarchar(18)");

                    b.Property<bool>("CurpActualizado")
                        .HasColumnType("bit");

                    b.Property<bool>("DependienteEconomico")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaFinal")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaSolicitud")
                        .HasColumnType("date");

                    b.Property<bool>("Fotos")
                        .HasColumnType("bit");

                    b.Property<bool>("Gobierno")
                        .HasColumnType("bit");

                    b.Property<string>("GradoFinalMilitar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradoFinalPolicia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradoInicioMilitar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradoInicioPolicia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ine")
                        .HasColumnType("bit");

                    b.Property<string>("JefeInmediato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Militar")
                        .HasColumnType("bit");

                    b.Property<string>("MotivoBaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NoAntecedentesPenales")
                        .HasColumnType("bit");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Policia")
                        .HasColumnType("bit");

                    b.Property<bool>("Privada")
                        .HasColumnType("bit");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<bool>("Revalorable")
                        .HasColumnType("bit");

                    b.Property<bool>("RfcHomoclave")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StatusExp")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoCasa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TelefonoEmpleo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoRecado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("coordenadasVivienda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorporacionId");

                    b.HasIndex("Curp");

                    b.HasIndex("RegionId");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("CuerpoRegion", b =>
                {
                    b.Property<string>("CuerposId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegionesId")
                        .HasColumnType("int");

                    b.HasKey("CuerposId", "RegionesId");

                    b.HasIndex("RegionesId");

                    b.ToTable("CuerpoRegion");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.CartaCompromiso", b =>
                {
                    b.HasOne("API.UnidadEmpleo.Domain.Solicitud", "Solicitud")
                        .WithMany("CartasCompromiso")
                        .HasForeignKey("IdSoliciud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Evaluacion", b =>
                {
                    b.HasOne("API.UnidadEmpleo.Domain.Solicitud", "Solicitud")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdSoliciud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Referencia", b =>
                {
                    b.HasOne("API.UnidadEmpleo.Domain.Solicitud", "Solicitud")
                        .WithMany("Referencias")
                        .HasForeignKey("IdSoliciud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Solicitud", b =>
                {
                    b.HasOne("API.UnidadEmpleo.Domain.Cuerpo", "Corporacion")
                        .WithMany()
                        .HasForeignKey("CorporacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.UnidadEmpleo.Domain.Aspirante", "Aspirante")
                        .WithMany("Solicitudes")
                        .HasForeignKey("Curp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.UnidadEmpleo.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aspirante");

                    b.Navigation("Corporacion");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CuerpoRegion", b =>
                {
                    b.HasOne("API.UnidadEmpleo.Domain.Cuerpo", null)
                        .WithMany()
                        .HasForeignKey("CuerposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.UnidadEmpleo.Domain.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Aspirante", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("API.UnidadEmpleo.Domain.Solicitud", b =>
                {
                    b.Navigation("CartasCompromiso");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Referencias");
                });
#pragma warning restore 612, 618
        }
    }
}
